name: Scrape-to-S3
on:
  # schedule:
  #   - cron: "*/5 * * * *"
  workflow_dispatch:
  repository_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
          aws-region: ap-southeast-2

      - name: Source 1
        run: |
          curl -s ${{ secrets.WGTI_URL }} > data.json
          aws s3 cp data.json s3://${{ secrets.BUCKET_NAME }}/WGTI/$(date -u +%Y/%m/%d/%H%M).json
      
      - name: Source 2
        run: |
          curl -s ${{ secrets.WGTO_URL }} > data.json
          aws s3 cp data.json s3://${{ secrets.BUCKET_NAME }}/WGTO/$(date -u +%Y/%m/%d/%H%M).json
          
      - name: Source 5
        run: |
         curl -X "GET" \
         "${{ secrets.VIC_API_URL }}" \
         -H "accept: application/json" \
         -H "KeyId: ${{ secrets.VIC_API_KEY }}" \
         | jq '.features | map(select(.properties.freewayName | contains("West Gate")))'
         # > west_gate.json
         # aws s3 cp west_gate.json s3://${{ secrets.BUCKET_NAME }}/govt/$(date -u +%Y/%m/%d/%H%M).json

      
      
